// Per-resource-type scaling script generator (ADR-010 Phase 2)
// 리소스 타입별 스케일링 스크립트 생성기 (ADR-010 Phase 2)
//
// Generates bash/kubectl commands. Scripts are EXPORTED for human review and
// manual execution. Phase 2 does NOT execute these — see ADR-010.

import type { ScalingPhase, ScalingTarget, ScalingResourceType, ScalingEvent } from '@/lib/event-scaling';

const SCRIPT_HEADER = `#!/bin/bash
# Pre-scaling script generated by AWSops (ADR-010 Phase 2)
# REVIEW EVERY COMMAND BEFORE RUNNING. AWSops does not execute these.
# 사전 스케일링 스크립트 — AWSops가 자동 생성. 실행 전 반드시 검토.
set -euo pipefail
`;

export function generateTargetScript(target: ScalingTarget): string {
  switch (target.resourceType) {
    case 'keda':
      return kedaScript(target);
    case 'hpa':
      return hpaScript(target);
    case 'aurora-replica':
      return auroraReplicaScript(target);
    case 'aurora-acu':
      return auroraAcuScript(target);
    case 'msk-broker':
      return mskBrokerScript(target);
    case 'msk-partition':
      return mskPartitionScript(target);
    case 'asg':
      return asgScript(target);
    case 'ec2':
      return ec2Script(target);
    case 'ebs-iops':
      return ebsIopsScript(target);
    case 'alb-capacity':
      return albCapacityScript(target);
    default:
      return `# UNSUPPORTED resourceType: ${target.resourceType as string}`;
  }
}

function kedaScript(t: ScalingTarget): string {
  // resourceId expected as "namespace/scaledobject-name"
  const [ns, name] = t.resourceId.includes('/') ? t.resourceId.split('/') : ['default', t.resourceId];
  return `# KEDA ScaledObject: ${t.resourceId} — minReplicaCount ${t.currentValue} → ${t.targetValue}
kubectl -n ${ns} patch scaledobject ${name} --type merge -p '{"spec":{"minReplicaCount":${t.targetValue}}}'`;
}

function hpaScript(t: ScalingTarget): string {
  const [ns, name] = t.resourceId.includes('/') ? t.resourceId.split('/') : ['default', t.resourceId];
  return `# HPA: ${t.resourceId} — minReplicas ${t.currentValue} → ${t.targetValue}
kubectl -n ${ns} patch hpa ${name} --type merge -p '{"spec":{"minReplicas":${t.targetValue}}}'`;
}

function auroraReplicaScript(t: ScalingTarget): string {
  // resourceId = cluster identifier; targetValue = desired replica count
  const delta = t.targetValue - t.currentValue;
  if (delta <= 0) {
    return `# Aurora ${t.resourceId}: already has ${t.currentValue} replicas (target ${t.targetValue}) — no action`;
  }
  const lines: string[] = [
    `# Aurora cluster ${t.resourceId} — add ${delta} read replicas (current ${t.currentValue} → target ${t.targetValue})`,
    `# Replicas inherit cluster instance class. Adjust --db-instance-class if needed.`,
  ];
  for (let i = 1; i <= delta; i++) {
    const id = `${t.resourceId}-prewarm-${Date.now()}-${i}`;
    lines.push(
      `aws rds create-db-instance-read-replica \\\n  --db-instance-identifier ${id} \\\n  --source-db-cluster-identifier ${t.resourceId} \\\n  --db-instance-class db.r6g.2xlarge`,
    );
  }
  lines.push(`# Cleanup script: aws rds delete-db-instance --db-instance-identifier <id> --skip-final-snapshot`);
  return lines.join('\n');
}

function auroraAcuScript(t: ScalingTarget): string {
  return `# Aurora Serverless v2 ACU: ${t.resourceId} — max ${t.currentValue} → ${t.targetValue} ACU
aws rds modify-db-cluster \\
  --db-cluster-identifier ${t.resourceId} \\
  --serverless-v2-scaling-configuration MinCapacity=0.5,MaxCapacity=${t.targetValue} \\
  --apply-immediately`;
}

function mskBrokerScript(t: ScalingTarget): string {
  // resourceId = MSK cluster ARN
  return `# MSK ${t.resourceId} — broker count ${t.currentValue} → ${t.targetValue}
# Note: only ALLOWS increasing. Requires current-version from describe-cluster.
CURRENT_VERSION=$(aws kafka describe-cluster --cluster-arn ${t.resourceId} --query 'ClusterInfo.CurrentVersion' --output text)
aws kafka update-broker-count \\
  --cluster-arn ${t.resourceId} \\
  --current-version "$CURRENT_VERSION" \\
  --target-number-of-broker-nodes ${t.targetValue}`;
}

function mskPartitionScript(t: ScalingTarget): string {
  // resourceId = "bootstrap:topic-name"
  const [bootstrap, topic] = t.resourceId.split(':');
  return `# MSK topic ${topic} on ${bootstrap} — partitions ${t.currentValue} → ${t.targetValue}
kafka-topics.sh --bootstrap-server ${bootstrap} --alter --topic ${topic} --partitions ${t.targetValue}`;
}

function asgScript(t: ScalingTarget): string {
  return `# ASG ${t.resourceId} — desired ${t.currentValue} → ${t.targetValue}
aws autoscaling set-desired-capacity \\
  --auto-scaling-group-name ${t.resourceId} \\
  --desired-capacity ${t.targetValue} \\
  --honor-cooldown
# If targetValue exceeds current Max, also raise it:
# aws autoscaling update-auto-scaling-group --auto-scaling-group-name ${t.resourceId} --max-size ${t.targetValue}`;
}

function ec2Script(t: ScalingTarget): string {
  return `# EC2 ${t.resourceId} — manual capacity adjustment ${t.currentValue} → ${t.targetValue}
# Implement via EC2 RunInstances or ASG. Generic placeholder:
echo 'TODO: replace with concrete RunInstances or ASG adjustment for ${t.resourceId}'`;
}

function ebsIopsScript(t: ScalingTarget): string {
  return `# EBS ${t.resourceId} — IOPS ${t.currentValue} → ${t.targetValue}
# Note: io2 takes ~6h to fully apply, gp3 is near-instant. Monitor with describe-volumes-modifications.
aws ec2 modify-volume \\
  --volume-id ${t.resourceId} \\
  --iops ${t.targetValue}
# Verify: aws ec2 describe-volumes-modifications --volume-ids ${t.resourceId}`;
}

function albCapacityScript(t: ScalingTarget): string {
  return `# ALB ${t.resourceId} — LCU pre-warming requested (${t.currentValue} → ${t.targetValue})
# AWS does not expose LCU pre-warming via API. File a Support case:
# https://console.aws.amazon.com/support/home#/case/create
# Subject: ALB pre-warming request for ${t.resourceId}
# Body: expected peak LCU = ${t.targetValue}, event window = <eventStart> to <eventEnd>
echo 'MANUAL ACTION: open AWS Support case for ALB pre-warming on ${t.resourceId}'`;
}

// --- Whole-event script export ---

export function generateEventScript(event: ScalingEvent): string {
  const plan = event.scalingPlan;
  if (!plan) return `${SCRIPT_HEADER}\n# No scaling plan generated yet for ${event.name}`;

  const lines: string[] = [
    SCRIPT_HEADER,
    '',
    `# Event: ${event.name}`,
    `# Window: ${event.eventStart} → ${event.eventEnd}`,
    `# Pattern: ${event.pattern.type} (${event.pattern.expectedPeakMultiplier}x peak)`,
    `# Generated: ${plan.generatedAt}`,
    `# Approved: ${plan.approvedAt || 'NOT APPROVED — review carefully'}`,
    '',
  ];

  for (const phase of plan.phases) {
    const offset = phase.scheduledOffsetMinutes;
    const sign = offset < 0 ? '-' : '+';
    const absMin = Math.abs(offset);
    const hh = Math.floor(absMin / 60);
    const mm = absMin % 60;
    const offsetLabel = offset === 0 ? 'T' : `T${sign}${hh > 0 ? `${hh}h` : ''}${mm > 0 ? `${mm}m` : ''}`;
    lines.push('');
    lines.push(`########## Phase ${phase.phaseNumber} (${offsetLabel}) — ${phase.label} ##########`);
    if (phase.notes) lines.push(`# ${phase.notes}`);
    lines.push('');
    for (const target of phase.targets) {
      if (target.rationale) lines.push(`# Rationale: ${target.rationale}`);
      lines.push(generateTargetScript(target));
      lines.push('');
    }
  }

  if (plan.estimatedAdditionalCostUsd != null) {
    lines.push(`# Estimated additional cost during event window: $${plan.estimatedAdditionalCostUsd.toFixed(2)}`);
  }
  return lines.join('\n');
}

// --- Apply script to event targets (mutates plan.phases.targets[].script) ---

export function fillScriptsIntoPlan(phases: ScalingPhase[]): ScalingPhase[] {
  return phases.map(p => ({
    ...p,
    targets: p.targets.map(t => ({ ...t, script: generateTargetScript(t) })),
  }));
}

export const SUPPORTED_RESOURCE_TYPES: ScalingResourceType[] = [
  'keda', 'hpa',
  'aurora-replica', 'aurora-acu',
  'msk-broker', 'msk-partition',
  'asg', 'ec2',
  'ebs-iops', 'alb-capacity',
];
