"""SG Rules & Usage — Athena/Glue broker Lambda (ADR-019 Role B isolation).

This is the ONLY principal in this repository allowed to `sts:AssumeRole` on the target account's
`AWSopsSgRuleAthenaRole` — the shared Fargate worker task role (worker_task, workers.tf) NEVER
gets that grant (ADR-019 §4 / the design spec's IAM section explicitly forbids it: granting it to
the shared role would expose every other job type this worker fleet runs to Athena/S3 access it
has no business needing). The Fargate worker (sg_rule_scan.py) and the web BFF (source validation,
web/lib/sg-rules.ts) both call this broker via `lambda:InvokeFunction` instead of assuming the
Athena role themselves — that grant is safe to give multiple callers because it does not confer
AssumeRole.

Two actions:
  - "validate": GetWorkGroup/GetDatabase/GetTable only (read-only existence + schema-resolution
    check backing the spec's "Flow Log source configuration" section). No query execution.
  - "query": run exactly ONE Athena SELECT (already fully generated by the caller — this module
    never accepts or forwards a caller-composed WHERE/column list; sg_rule_scan.py builds the SQL
    text from validated, allowlisted identifiers before ever reaching here) for one account/region/
    day partition: StartQueryExecution -> poll GetQueryExecution -> GetQueryResults (paginated) ->
    StopQueryExecution on deadline/budget-exceeded. Structurally the same shape as CloudWatch Logs
    Insights' StartQuery/poll/GetQueryResults/StopQuery pattern already live in web/lib/dns-logs.ts
    / anfw-logs.ts / nfm.ts (ADR-019 §2).

Never executes a caller-supplied WHERE/column list, never runs anything but SELECT (the query
string is validated defense-in-depth here too — see _reject_non_select), never touches
CreateWorkGroup/CreateTable/DeleteTable/etc, and never writes S3 outside the workgroup's own
configured result location (that write is Athena's own intrinsic mechanic, not something this
module does directly).
"""
import os
import re
import time

import boto3

_STS_SESSION_NAME = "awsops-sg-rule-athena"
_POLL_INTERVAL_S = 1.0
_MAX_POLL_S = int(os.environ.get("SG_RULE_ATHENA_POLL_TIMEOUT_S", "120"))
_DEFAULT_MAX_BYTES = int(os.environ.get("SG_RULE_ACTIVITY_MAX_QUERY_BYTES", "107374182400"))  # 100 GiB
_ROLE_NAME = "AWSopsSgRuleAthenaRole"

# Defense-in-depth: even though sg_rule_scan.py only ever builds a validation-generated SELECT
# (§3b control 1 of ADR-019), this broker independently refuses anything that isn't a bare SELECT
# before it ever reaches Athena — a second, structurally-different check in a different process.
_SELECT_ONLY_RE = re.compile(r"^\s*SELECT\b", re.IGNORECASE)
_FORBIDDEN_RE = re.compile(
    r"\b(INSERT|UPDATE|DELETE|DROP|ALTER|CREATE|GRANT|REVOKE|MERGE|TRUNCATE|CALL|VACUUM|UNLOAD)\b",
    re.IGNORECASE,
)


class BrokerError(Exception):
    pass


def _reject_non_select(sql):
    if not _SELECT_ONLY_RE.match(sql or ""):
        raise BrokerError("query must be a bare SELECT")
    if _FORBIDDEN_RE.search(sql):
        raise BrokerError("query contains a forbidden (mutating) keyword")


def _assumed_session(account_id, external_id, region):
    sts = boto3.client("sts", region_name=region)
    role_arn = f"arn:aws:iam::{account_id}:role/{_ROLE_NAME}"
    kwargs = {"RoleArn": role_arn, "RoleSessionName": _STS_SESSION_NAME, "DurationSeconds": 3600}
    if external_id:
        kwargs["ExternalId"] = external_id
    resp = sts.assume_role(**kwargs)
    c = resp["Credentials"]
    return boto3.Session(
        aws_access_key_id=c["AccessKeyId"], aws_secret_access_key=c["SecretAccessKey"],
        aws_session_token=c["SessionToken"], region_name=region,
    )


def _validate(event):
    account_id = event["account_id"]
    region = event["region"]
    external_id = event.get("external_id")
    workgroup = event["workgroup"]
    database = event["database"]
    table = event["table"]
    session = _assumed_session(account_id, external_id, region)
    athena = session.client("athena")
    glue = session.client("glue")

    wg = athena.get_work_group(WorkGroup=workgroup)
    result_config = (wg.get("WorkGroup", {}).get("Configuration", {}) or {}).get("ResultConfiguration", {})
    if not result_config.get("OutputLocation"):
        raise BrokerError("workgroup has no configured query-results S3 location")

    glue.get_database(Name=database)
    tbl = glue.get_table(DatabaseName=database, Name=table)["Table"]
    columns = [c["Name"].lower() for c in tbl.get("StorageDescriptor", {}).get("Columns", [])]
    # Canonical VPC Flow Log fields (+ their Athena underscore-normalized forms).
    required = {
        "interface_id": ["interface-id", "interface_id"],
        "srcaddr": ["srcaddr"], "dstaddr": ["dstaddr"],
        "srcport": ["srcport"], "dstport": ["dstport"],
        "protocol": ["protocol"], "action": ["action"], "log_status": ["log-status", "log_status"],
        "start": ["start"], "end": ["end"],
    }
    resolved = {}
    missing = []
    for canonical, aliases in required.items():
        hit = next((a for a in aliases if a.lower() in columns), None)
        if hit:
            resolved[canonical] = hit
        else:
            missing.append(canonical)
    if missing:
        raise BrokerError(f"table missing required Flow Log fields: {', '.join(missing)}")

    partition_keys = [c["Name"] for c in tbl.get("PartitionKeys", [])]
    projection_enabled = (tbl.get("Parameters", {}) or {}).get("projection.enabled") == "true"
    if not partition_keys and not projection_enabled:
        raise BrokerError("table has no partition keys or partition projection — cannot bound a scan")
    strategy = "projection" if projection_enabled else "partition_keys"

    optional_present = [c for c in ("flow-direction", "flow_direction", "tcp-flags", "tcp_flags",
                                    "bytes", "packets") if c.lower() in columns]
    return {
        "ok": True, "schemaFields": sorted(resolved.values()), "partitionStrategy": strategy,
        "optionalFields": optional_present,
    }


def _query(event):
    account_id = event["account_id"]
    region = event["region"]
    external_id = event.get("external_id")
    workgroup = event["workgroup"]
    database = event["database"]
    query = event["query"]
    max_bytes = int(event.get("max_bytes") or _DEFAULT_MAX_BYTES)
    _reject_non_select(query)

    session = _assumed_session(account_id, external_id, region)
    athena = session.client("athena")

    start = athena.start_query_execution(
        QueryString=query,
        QueryExecutionContext={"Database": database},
        WorkGroup=workgroup,
    )
    qid = start["QueryExecutionId"]
    deadline = time.time() + _MAX_POLL_S
    status = None
    scanned_bytes = 0
    while time.time() < deadline:
        exec_ = athena.get_query_execution(QueryExecutionId=qid)["QueryExecution"]
        status = exec_["Status"]["State"]
        scanned_bytes = int((exec_.get("Statistics") or {}).get("DataScannedInBytes") or 0)
        if status in ("SUCCEEDED", "FAILED", "CANCELLED"):
            break
        time.sleep(_POLL_INTERVAL_S)
    else:
        # Deadline hit while still running/queued -> best-effort cancel, then report a clean error.
        try:
            athena.stop_query_execution(QueryExecutionId=qid)
        except Exception:  # noqa: BLE001
            pass
        return {"ok": False, "reason": "poll deadline exceeded", "query_execution_id": qid}

    if status != "SUCCEEDED":
        reason = (exec_.get("Status", {}) or {}).get("StateChangeReason", status)
        return {"ok": False, "reason": reason, "query_execution_id": qid, "status": status}

    if scanned_bytes > max_bytes:
        # Athena already finished (the workgroup's own BytesScannedCutoffPerQuery is the primary
        # hard cutoff during execution); this is the post-hoc budget check the spec's
        # sg_rule_activity_max_query_bytes gate requires — never return rows over budget.
        return {
            "ok": False, "reason": "scan-bytes budget exceeded", "query_execution_id": qid,
            "data_scanned_bytes": scanned_bytes,
        }

    rows = []
    columns = None
    next_token = None
    first_page = True
    while True:
        kwargs = {"QueryExecutionId": qid, "MaxResults": 1000}
        if next_token:
            kwargs["NextToken"] = next_token
        page = athena.get_query_results(**kwargs)
        result_rows = page["ResultSet"]["Rows"]
        if first_page:
            # First row of the first page is the header row (column names) per Athena's contract.
            if columns is None and result_rows:
                columns = [c.get("VarCharValue") for c in result_rows[0]["Data"]]
            result_rows = result_rows[1:]
            first_page = False
        for r in result_rows:
            values = [c.get("VarCharValue") for c in r["Data"]]
            rows.append(dict(zip(columns or [], values)))
        next_token = page.get("NextToken")
        if not next_token:
            break

    return {
        "ok": True, "rows": rows, "data_scanned_bytes": scanned_bytes, "query_execution_id": qid,
    }


def lambda_handler(event, _ctx):
    action = event.get("action")
    try:
        if action == "validate":
            return _validate(event)
        if action == "query":
            return _query(event)
        return {"ok": False, "reason": f"unknown action: {action!r}"}
    except BrokerError as e:
        return {"ok": False, "reason": str(e)}
    except Exception as e:  # noqa: BLE001 — never let a raw AWS exception leak un-shaped
        return {"ok": False, "reason": f"{type(e).__name__}: {e}"}
